class Constants:
    BOARD_POSITION_MIN = 1
    BOARD_POSITION_MAX = 100
    BOARD_ROW_SIZE = 10
    BOARD_LAST_LUCKY_ZONE_BEGIN = 94 + 1

    PLAYER_START_POSITION = 0

    DIE_ROLL_MIN = 1
    DIE_ROLL_MAX = 6
    DIE_ROLL_REPEAT = DIE_ROLL_MAX
